version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - echo "Preparing app for deployment..."
      - mkdir -p deploy
      - cp target/shop-0.0.1-SNAPSHOT.jar deploy/
      - cp appspec.yml deploy/
      - cp -r scripts deploy/
      - cd deploy
      - zip -r ../app.zip .
      - cd ..
      - mkdir -p output
      - mv app.zip output/
      - chmod +x deploy/scripts/start.sh

artifacts:
  files:
    - output/app.zip
  discard-paths: yes
