version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - mvn clean package -DskipTests=true
      - mkdir -p deploy
      - cp target/*.jar deploy/
      - cd deploy
      - zip -r ../app.zip .
      - cd ..
artifacts:
  files:
    - app.zip
  discard-paths: yes
